// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHjjj8kByGMabfiTqa-VevzZn8fr82GI',
    appId: '1:217065370781:web:4cd005f7b6e05c3fb2d074',
    messagingSenderId: '217065370781',
    projectId: 'virtualpetapp-d3c0d',
    authDomain: 'virtualpetapp-d3c0d.firebaseapp.com',
    storageBucket: 'virtualpetapp-d3c0d.firebasestorage.app',
    measurementId: 'G-FNH6LT6TE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9oeqBCaejr2fPY2DSKh54lHP3LfHRinI',
    appId: '1:217065370781:android:27f7e9027c5bf557b2d074',
    messagingSenderId: '217065370781',
    projectId: 'virtualpetapp-d3c0d',
    storageBucket: 'virtualpetapp-d3c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBND6lw49m5P93Q9TT7HCNWsnZJ7rl4jO8',
    appId: '1:217065370781:ios:f1b22f7708409173b2d074',
    messagingSenderId: '217065370781',
    projectId: 'virtualpetapp-d3c0d',
    storageBucket: 'virtualpetapp-d3c0d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBND6lw49m5P93Q9TT7HCNWsnZJ7rl4jO8',
    appId: '1:217065370781:ios:f1b22f7708409173b2d074',
    messagingSenderId: '217065370781',
    projectId: 'virtualpetapp-d3c0d',
    storageBucket: 'virtualpetapp-d3c0d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaHjjj8kByGMabfiTqa-VevzZn8fr82GI',
    appId: '1:217065370781:web:f950cc24ceef662fb2d074',
    messagingSenderId: '217065370781',
    projectId: 'virtualpetapp-d3c0d',
    authDomain: 'virtualpetapp-d3c0d.firebaseapp.com',
    storageBucket: 'virtualpetapp-d3c0d.firebasestorage.app',
    measurementId: 'G-SGWGS7TSVS',
  );
}
